apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: aide-pi
spec:
  hosts:
  - ssh:
      address: 10.203.1.200
      user: pi
      port: 22
      keyPath: ~/.ssh/id_pi200
    role: controller
    uploadBinary: false
    os: debian
  - ssh:
      address: 10.203.1.201
      user: orangepi
      port: 22
      keyPath: ~/.ssh/id_pi201
    role: worker
    uploadBinary: true
    os: ubuntu
  - ssh:
      address: 10.203.1.202
      user: orangepi
      port: 22
      keyPath: ~/.ssh/id_pi202
    role: worker
    uploadBinary: true
    os: ubuntu
  k0s:
    version: 1.28.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: aide
      spec:
        api:
          sans:
            - 103.206.205.154
        extensions:
          helm:
            repositories:
            - name: traefik
              url: https://helm.traefik.io/traefik
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            - name: openebs
              url: https://openebs.github.io/charts
            charts:
            - name: openebs
              chartname: openebs/openebs
              version: "3.9.0"
              namespace: kube-system
            - name: traefik
              chartname: traefik/traefik
              version: "24.0.0"
              namespace: kube-system
            - name: metallb
              chartname: bitnami/metallb
              version: "4.7.3"
              namespace: kube-system

          storage:
            create_default_storage_class: true
            type: openebs_local_storage
        telemetry:
          enabled: false
