deployment:
  enabled: true
  kind: Deployment
  replicas: 2

# Traefik experimental features
experimental:
  # -- Enable traefik experimental plugins
  plugins:
    middleflare:
      moduleName: github.com/neggles/middleflare
      version: v0.0.2
    cloudflarewarp:
      moduleName: github.com/BetterCorp/cloudflarewarp
      version: v1.3.3
    superrate:
      moduleName: github.com/bukukasio/super-rate
      version: v0.0.3
    # - --experimental.plugins.traefik-real-ip.modulename=github.com/soulbalz/traefik-real-ip
    # - --experimental.plugins.traefik-real-ip.version=v1.0.3
    # - --experimental.plugins.traefik-jwt-plugin.modulename=github.com/team-carepay/traefik-jwt-plugin
    # - --experimental.plugins.traefik-jwt-plugin.version=v0.5.1
    # - --experimental.plugins.staticresponse.modulename=github.com/jdel/staticresponse
    # - --experimental.plugins.staticresponse.version=v0.0.1
    # - --experimental.plugins.traefik-plugin-cors-preflight.modulename=github.com/Medzoner/traefik-plugin-cors-preflight
    # - --experimental.plugins.traefik-plugin-cors-preflight.version=v1.0.6
    # - --experimental.plugins.traefik-request-id.modulename=github.com/ZeroGachis/traefik-request-id
    # - --experimental.plugins.traefik-request-id.version=v0.1.5
    # - --experimental.plugins.traefik-plugin-blockuseragent.modulename=github.com/agence-gaya/traefik-plugin-blockuseragent
    # - --experimental.plugins.traefik-plugin-blockuseragent.version=v0.1.5
    # - --experimental.plugins.traefik-cache.modulename=github.com/ghnexpress/traefik-cache
    # - --experimental.plugins.traefik-cache.version=v0.0.9


providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

  kubernetesIngress:
    enabled: true

logs:
  general:
    format: json
    # By default, the level is set to ERROR.
    # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: ERROR
  access:
    enabled: true
    format: json
    bufferingSize: 100


metrics:
  ## -- Prometheus is enabled by default.
  ## -- It can be disabled by setting "prometheus: null"
  prometheus:
    entryPoint: metrics

  influxdb:
     ## Address instructs exporter to send metrics to influxdb at this address.
     address: database.influxdb:8089
     ## InfluxDB's address protocol (udp or http). Default="udp"
     protocol: udp
     ## InfluxDB database used when protocol is http. Default=""
     # database: ""
     ## InfluxDB retention policy used when protocol is http. Default=""
     # retentionPolicy: ""
     ## InfluxDB username (only with http). Default=""
     # username: ""
     ## InfluxDB password (only with http). Default=""
     # password: ""
     ## The interval used by the exporter to push metrics to influxdb. Default=10s
     # pushInterval: 30s
     ## Additional labels (influxdb tags) on all metrics.
     # additionalLabels:
     #   env: production
     #   foo: bar
     ## Enable metrics on entry points. Default=true
     # addEntryPointsLabels: false
     ## Enable metrics on routers. Default=false
     # addRoutersLabels: true
     ## Enable metrics on services. Default=true
     # addServicesLabels: false


# -- Global command arguments to be passed to all traefik's pods
globalArguments:
  - --entrypoints.postgres.address=:5432/tcp
  - --entrypoints.mongo.address=:27017/tcp


# Configure Traefik static configuration
# -- Additional arguments to be passed at Traefik's binary
# All available options available on https://docs.traefik.io/reference/static-configuration/cli/
## Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
additionalArguments: []
#  - "--providers.kubernetesingress.ingressclass=traefik-internal"
#  - "--log.level=DEBUG"
