[server]
# Protocol (http, https, h2, socket)
protocol = http

http_addr =
http_port = 3000
domain = localhost
enable_gzip = true
;enforce_domain = false
;root_url = %(protocol)s://%(domain)s:%(http_port)s/
;serve_from_sub_path = false
;router_logging = false
;static_root_path = public


